doctrine_migrations:
    migrations_paths:
<<<<<<< HEAD
<<<<<<< HEAD
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
=======
=======
>>>>>>> d664e075a17421c70a80815d4279db3c4ec8eaef
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
    em: default






# Configureer dat de wijzigingen worden opgeslagen die worden verwijderd en worden toegevoegd


# SQL import soort van

# Schrijf entity files voor elke tabel in het project
<<<<<<< HEAD
# 
>>>>>>> d2ce24c (compose.yaml, docker & entity)
=======
# 
>>>>>>> d664e075a17421c70a80815d4279db3c4ec8eaef
