doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
    em: default






# Configureer dat de wijzigingen worden opgeslagen die worden verwijderd en worden toegevoegd


# SQL import soort van

# Schrijf entity files voor elke tabel in het project
# 