doctrine_migrations:
    migrations_paths:
<<<<<<< HEAD
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
=======
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            executed_at_column_name: 'executed_at'
    connection: default






# Configureer dat de wijzigingen worden opgeslagen die worden verwijderd en worden toegevoegd


# SQL import soort van

# Schrijf entity files voor elke tabel in het project
# 
>>>>>>> d2ce24c (compose.yaml, docker & entity)
