services:
  database:
    image: mariadb:latest
    container_name: devhub_lexact-database
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1477
      MYSQL_DATABASE: devhub_lexact_db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_PORT: 3308
      DB_DATABASE: devhub_lexact_db
      DB_USERNAME: root
      DB_PASSWORD: 1477
    command: [ "php", "-S", "0.0.0.0:8800", "-t", "/var/www/html/public" ]